Download area
dbcls/togosite pull request #100
Opened 2021-06-14 09:11 UTC by ryuta-oe

download areaのTSV、ワンクリックダウンロード、editロゴ修正等を行いました。
ご確認よろしくお願いいたします。

2021-06-14 09:40 UTC, penqe requested changes
レビューしました

2021-06-14 09:40 UTC, penqe commented on frontend/source/css/object/component/_table-data-controller-view.sass
> +    > [data-button="download-json"],[data-button="download-tsv"]
`> [data-button="download-json"], > [data-button="download-tsv"]`
としてください

2021-06-14 09:40 UTC, penqe commented on frontend/source/css/object/component/_table-data-controller-view.sass
> +          width: 16px
単位は合わせたいので、`1.6rem` にしてください

2021-06-14 09:40 UTC, penqe commented on frontend/source/css/object/component/_table-data-controller-view.sass
> +      > [data-button="download-json"],[data-button="download-tsv"]
同上

2021-06-14 09:40 UTC, penqe commented on frontend/source/js/classes/TableData.js
> +    let temporaryArray = [];
`const` でよいはず

2021-06-14 09:40 UTC, penqe commented on frontend/source/js/classes/TableData.js
> +        let singleItem;
`const singleItem = {`
という書き方で良い？

2021-06-14 09:40 UTC, penqe commented on frontend/source/js/classes/TableData.js
> +      let tsvArray = [];
const でよいはず

2021-06-14 09:40 UTC, penqe commented on frontend/source/js/classes/TableData.js
> +      tsvArray.push(Object.keys(temporaryArray[0]) + "\n");
あまりよくわかってないけど、末尾の `"\n"` はどのような意味がありますか？

2021-06-14 09:40 UTC, penqe commented on frontend/source/js/classes/TableData.js
> +      temporaryArray.map(item => {
このような場合は `map` ではなく `forEach` を使うべき

2021-06-14 09:40 UTC, penqe commented on frontend/source/js/classes/TableData.js
> +      this.#BUTTON_DOWNLOAD_TSV.querySelector(':scope > .tsv').setAttribute('href', tsvUrl);
2回同じセレクタを実行しているので、1回にまとめる

2021-06-14 10:05 UTC, ryuta-oe commented on frontend/source/js/classes/TableData.js
> +      tsvArray.push(Object.keys(temporaryArray[0]) + "\n");
"\n" は改行の意味になります。配列をtsv化する際、小配列（singleItem）の末尾で改行してあげないと、２行目に来るべき小配列が右側に延々と出力されてしまいます。それを防ぎ、１行につき１小配列ずつ改行して並べていくために付与しています。うまく説明できてなくてすみません。

2021-06-14 14:00 UTC, penqe commented on frontend/source/js/classes/TableData.js
> +      tsvArray.push(Object.keys(temporaryArray[0]) + "\n");
@ryuta-oe なるほど。自分なら、多次元配列にして、デリミタで改行を渡す、というふうにするかと思います。でも動いているのなら良いかな。
ちなみにこの書き方だと、行末に不要なタブが入りませんか？

2021-06-15 01:36 UTC, ryuta-oe commented on frontend/source/css/object/component/_table-data-controller-view.sass
> +    > [data-button="download-json"],[data-button="download-tsv"]
対応いたしました。

2021-06-15 01:36 UTC, ryuta-oe commented on frontend/source/css/object/component/_table-data-controller-view.sass
> +          width: 16px
対応いたしました。

2021-06-15 01:37 UTC, ryuta-oe commented on frontend/source/css/object/component/_table-data-controller-view.sass
> +      > [data-button="download-json"],[data-button="download-tsv"]
対応いたしました。

2021-06-15 01:40 UTC, ryuta-oe commented on frontend/source/js/classes/TableData.js
> +    let temporaryArray = [];
対応いたしました。

2021-06-15 01:42 UTC, ryuta-oe commented on frontend/source/js/classes/TableData.js
> +        let singleItem;
ご指摘のとおりで問題ないので、修正いたしました。

2021-06-15 01:43 UTC, ryuta-oe commented on frontend/source/js/classes/TableData.js
> +      let tsvArray = [];
対応いたしました。

2021-06-15 01:44 UTC, ryuta-oe commented on frontend/source/js/classes/TableData.js
> +      temporaryArray.map(item => {
対応いたしました。

2021-06-15 01:45 UTC, ryuta-oe commented on frontend/source/js/classes/TableData.js
> +      this.#BUTTON_DOWNLOAD_TSV.querySelector(':scope > .tsv').setAttribute('href', tsvUrl);
json,tsv共に修正いたしました。

2021-06-15 02:12 UTC, penqe requested changes

2021-06-15 02:12 UTC, penqe commented on frontend/source/js/classes/TableData.js
> +    if ((this.offset >= this.#queryIds.length)) {
いったん、この if 文を外してもらえますか？
あるいは // TODO: をつけて、後で外す必要があることを記述してもらうか

2021-06-15 02:12 UTC, penqe commented on frontend/source/js/classes/TableData.js
> +    // set lavel
不要な部分は消す
（後で復活する可能性があるようであれば、その旨記述してください

2021-06-15 02:12 UTC, penqe commented on frontend/source/js/classes/TableData.js
> +      this.#rows.map(row => {
インデントがおかしい

2021-06-15 02:12 UTC, penqe commented on frontend/source/js/classes/TableData.js
> +          attribute: row.properties[0].propertyId,
ちょっと気になったのだけど、この書き方でも、たとえば横に長いテーブルも漏れなくTSVに落とし込めてますか？
あまりこのロジックを理解できてないかもだけど。。。

2021-06-15 02:17 UTC, ryuta-oe commented on frontend/source/js/classes/TableData.js
> +    if ((this.offset >= this.#queryIds.length)) {
いったん削除しておきました。

2021-06-15 02:18 UTC, ryuta-oe commented on frontend/source/js/classes/TableData.js
> +    // set lavel
いったん削除しておきました。

2021-06-15 02:19 UTC, ryuta-oe commented on frontend/source/js/classes/TableData.js
> +      this.#rows.map(row => {
修正いたしました。

2021-06-15 06:16 UTC, ryuta-oe commented on frontend/source/js/classes/TableData.js
> +          attribute: row.properties[0].propertyId,
うまく落とし込めておりませんでしたので、修正いたしました。
仕上がりのTSVサンプルを別途送付します。

2021-06-17 05:18 UTC, ryuta-oe commented on frontend/source/js/classes/TableData.js
> +      tsvArray.push(Object.keys(temporaryArray[0]) + "\n");
ご指摘のとおり修正いたしました。

2021-06-17 05:22 UTC, penqe approved these changes

2021-06-17 05:23 UTC, penqe commented
@inutano レビューしました。マージお願いします。
古いブランチなので、コンフリクトいろいろ起こりそうです。

2021-06-21 01:44 UTC, merged

2021-06-21 01:45 UTC, inutano commented
@ryuta-oe @penqe  ありがとうございます！！！