Update progress bar
dbcls/togosite pull request #156
Opened 2021-07-21 10:56 UTC by MarleenEliza

- Add simple variant of Progress bar (without time and counter)
- Add progress bar animation when Mapping IDs
- Fix bug upon resetting mapping IDs
- Small code improvements

2021-07-22 00:40 UTC, penqe requested changes
CSSにコメントしました

2021-07-22 00:40 UTC, penqe commented on frontend/source/css/object/component/_progress-indicator.sass
> +    div.-fetching &, div[data-status="load rows"] &, div[data-status="complete"] &
`div` は必要でなければ省略しても良いです

2021-07-22 00:40 UTC, penqe commented on frontend/source/css/object/component/_progress-indicator.sass
> +    div[data-status="load rows"] &, div[data-status="complete"] &
同上

2021-07-22 00:40 UTC, penqe commented on frontend/source/css/object/component/_progress-indicator.sass
> +    div.-fetching &
同上

2021-07-22 00:40 UTC, penqe commented on frontend/source/css/object/component/_progress-indicator.sass
> +    div[data-status="complete"] &
同上

2021-07-22 00:40 UTC, penqe commented on frontend/source/css/object/component/_progress-indicator.sass
> +    div[data-status="complete"] &
同上

2021-07-26 01:46 UTC, MarleenEliza commented
> CSSにコメントしました

レビューありがとうございます！CSSを修正しましたのでご確認をお願いいたします。

2021-07-26 02:53 UTC, penqe approved these changes

2021-07-26 02:53 UTC, penqe commented
@inutano マージお願いします。mm

2021-07-26 07:13 UTC, merged

2021-07-26 07:14 UTC, inutano commented
ありがとうございます！！