Download area
dbcls/togosite pull request #50
Opened 2021-05-20 06:14 UTC by ryuta-oe

前回のレビュー内容を修正しましたので、よろしくお願いします。

2021-05-20 06:26 UTC, inutano commented
ちなみにプルリクを作り直さないでも、既に送ったPRのブランチで修正して再度pushすると、修正で上書きできますのでご参考まで〜

2021-05-20 06:31 UTC, ryuta-oe commented
ありがとうございます！ぜひ次回の参考にさせていただきます！

2021-05-21 02:29 UTC, penqe requested changes
レビューしました

2021-05-21 02:29 UTC, penqe commented on frontend/source/js/classes/TableData.js
> +        this.#BUTTON_PREPARE_DOWNLOAD.querySelector('.autorenew').classList.add('lotation');
探索空間を狭くする

2021-05-21 02:29 UTC, penqe commented on frontend/source/js/classes/TableData.js
> +    this.#BUTTON_PREPARE_DOWNLOAD.querySelector('.autorenew').classList.add('lotation');
探索空間

2021-05-21 03:20 UTC, ryuta-oe commented
ご指摘の件、修正の上pushしたので、改めてご確認をお願いします！

2021-05-24 00:10 UTC, penqe requested changes

2021-05-24 00:10 UTC, penqe commented on frontend/source/js/classes/TableData.js
> +        <a class="JSON" href="" download="sample.json">
RSCSS の命名規約だと、スモールケースになります

2021-05-24 00:10 UTC, penqe commented on frontend/source/js/classes/TableData.js
> +        this.#BUTTON_PREPARE_DOWNLOAD.querySelector('.autorenew').classList.add('lotation');
querySelector は極力 :scope > から始めてください。

2021-05-24 00:10 UTC, penqe commented on frontend/source/js/classes/TableData.js
> +    this.#BUTTON_PREPARE_DOWNLOAD.querySelector('.autorenew').classList.add('lotation');
探索空間

2021-05-24 00:10 UTC, penqe commented on frontend/source/js/classes/TableData.js
> +    this.#BUTTON_START_DOWNLOAD.querySelector('.JSON').setAttribute('href', jsonUrl);
探索空間

2021-05-25 06:01 UTC, penqe approved these changes

2021-05-25 08:59 UTC, inutano commented
conflictしてますね、僕は中身わからないのでお二方どちらかにresolve conflictsお願いしたく 🙏

2021-05-25 10:45 UTC, merged