Add popup with stanza
dbcls/togosite pull request #59
Opened 2021-05-26 11:52 UTC by MarleenEliza

Add a modal popup screen showing the stanza when clicking on Entries in ResultsTable

2021-05-26 13:48 UTC, penqe requested changes

2021-05-27 12:31 UTC, MarleenEliza commented on frontend/source/js/classes/ResultDetailModal.js
>  import App from "./App";
そもそもAppは必要ないとのことだったので削除しました。

2021-05-27 12:32 UTC, MarleenEliza commented on frontend/source/css/object/project/_ResultDetailModal.sass
> +        strong
Sassがあまり強くなくてすみません。前にも同じことを教えていただいた覚えがあります。。
修正しました。

2021-05-27 12:33 UTC, MarleenEliza commented on frontend/source/css/object/project/_ResultDetailModal.sass
> +          &> *
上記通りに対応しました。

2021-05-27 12:34 UTC, MarleenEliza commented on frontend/source/js/classes/Records.js
> +    return this.#subjects.find(subject => subject.subjectId === subjectId );
上記通りに対応しました。

2021-05-27 12:35 UTC, MarleenEliza commented on frontend/source/js/classes/ResultsTable.js
>  import DefaultEventEmitter from "./DefaultEventEmitter";
上記通りに対応しました。

2021-05-27 12:35 UTC, MarleenEliza commented on frontend/source/js/classes/ResultDetailModal.js
> +    const mainCategory = props.isReport ? ``: Records.getProperty(keys.mainCategoryId);
上記通りに対応しました。

2021-05-27 12:37 UTC, MarleenEliza commented on frontend/source/js/classes/ResultDetailModal.js
> +    stanzaContainer.innerHTML += `
ありがとうございます！RSCSSのルールに従うように修正しました。
また、Arrowでの移動機能も追加しましたの少し全体的に書き方を変更しました。

2021-05-27 20:06 UTC, penqe requested changes

2021-05-27 20:06 UTC, penqe commented on frontend/source/js/classes/ResultsTable.js
> +                  data-order = "${[columnIndex + 1, index]}"
細かくてすみませんが、「=」の前後の space を消してください。

2021-05-27 20:06 UTC, penqe commented on frontend/source/js/classes/ResultsTable.js
> +                  href="${attribute.attribute ? attribute.attribute.uri : ""}"
ここも細かくなってしまいますが、"" は '' にしてください。

2021-05-27 20:06 UTC, penqe commented on frontend/source/js/classes/ResultsTable.js
> +                  data-main-category-id="${
この辺りの dataset名は、後で変わるかもしれませんね

2021-05-28 00:52 UTC, MarleenEliza commented on frontend/source/js/classes/Records.js
> +        .map((channel) => channel * 256)
失礼しました、上記のRecords.js意図的な修正ではありません。おっしゃる通りにPrettifierを使っています。
現在の`frontend`ブランチに合わせます。

2021-05-28 00:54 UTC, MarleenEliza commented on frontend/source/js/classes/ResultDetailModal.js
> +    this.#ROOT.id = "ResultDetailModal";
idでもsingle quoteになりますか？　HTMLElementだけがSingle Quoteになると思いましたが、何かを勘違いしているのでしょうか？

2021-05-28 00:54 UTC, MarleenEliza commented on frontend/source/js/classes/ResultDetailModal.js
> +    } catch (error) {
こちらについては改めてご相談させてください。

2021-05-28 00:58 UTC, MarleenEliza commented on frontend/source/js/classes/ResultsTable.js
> +            <a class="toreportpage" href="report.html?togoKey=${
はい、Formatterです。この方が個人的にも読みやすいと思いましたのでこのままで置いておきました。前に戻した方が宜しいでしょうか？

2021-05-28 20:48 UTC, closed without merging