Download area
dbcls/togosite pull request #64
Opened 2021-05-27 10:48 UTC by ryuta-oe

developブランチ移行に向け、一旦downloadAreaブランチのマージをお願いします。

2021-05-27 11:04 UTC, penqe requested changes

2021-05-27 11:04 UTC, penqe commented on frontend/source/js/classes/TableData.js
> +        <span class="material-icons-outlined">settings_backup_restore</span><span>Edit</span>
span タグは必要ですか？

2021-05-27 11:04 UTC, penqe commented on frontend/source/js/classes/TableData.js
>          this.#isAutoLoad == true;
this.#isAutoLoad == true

この文は何を意図してますか？

2021-05-27 11:04 UTC, penqe commented on frontend/source/js/classes/TableData.js
> +        this.#BUTTON_PREPARE_DOWNLOAD.querySelector(':scope > .prepare-pause-resume').innerHTML='Pause';
細かくて申し訳ないですが、「=」の両端にスペースを設けてください

2021-05-27 11:04 UTC, penqe commented on frontend/source/js/classes/TableData.js
> +        this.#BUTTON_PREPARE_DOWNLOAD.querySelector(':scope > .prepare-pause-resume').innerHTML='Resume';
同上

2021-05-27 11:04 UTC, penqe commented on frontend/source/js/classes/TableData.js
> +      console.log('restore');
不要なログ

2021-05-27 11:04 UTC, penqe commented on frontend/source/js/classes/TableData.js
> +            console.log(Records.getValue(attribute.query.propertyId, categoryId));
log

2021-05-27 11:04 UTC, penqe commented on frontend/source/js/classes/TableData.js
> +          values: [{
ここは何を意図してますか

2021-05-27 11:33 UTC, ryuta-oe commented on frontend/source/js/classes/TableData.js
> +        <span class="material-icons-outlined autorenew">autorenew</span><span class="prepare-pause-resume">Prepare Data</span>
prepare-dataに変更しました。

2021-05-27 11:33 UTC, ryuta-oe commented on frontend/source/js/classes/TableData.js
> +        <span class="material-icons-outlined">settings_backup_restore</span><span>Edit</span>
不要なため削除しました。

2021-05-27 11:34 UTC, ryuta-oe commented on frontend/source/js/classes/TableData.js
>          this.#isAutoLoad == true;
不要なため削除しました。

2021-05-27 11:34 UTC, ryuta-oe commented on frontend/source/js/classes/TableData.js
> +        this.#BUTTON_PREPARE_DOWNLOAD.querySelector(':scope > .prepare-pause-resume').innerHTML='Pause';
両端にスペースを設けました。

2021-05-27 11:34 UTC, ryuta-oe commented on frontend/source/js/classes/TableData.js
> +        this.#BUTTON_PREPARE_DOWNLOAD.querySelector(':scope > .prepare-pause-resume').innerHTML='Resume';
同上

2021-05-27 11:35 UTC, ryuta-oe commented on frontend/source/js/classes/TableData.js
> +      console.log('restore');
不要なため削除しました。

2021-05-27 11:35 UTC, ryuta-oe commented on frontend/source/js/classes/TableData.js
> +            console.log(Records.getValue(attribute.query.propertyId, categoryId));
不要なため削除しました。

2021-05-27 11:35 UTC, ryuta-oe commented on frontend/source/js/classes/TableData.js
> +          values: [{
実装途中コードのためコメントアウトにしました。

2021-05-27 11:41 UTC, penqe requested changes
一箇所コメントしました

2021-05-27 11:41 UTC, penqe commented on frontend/source/js/classes/TableData.js
> +        <span class="material-icons-outlined autorenew">autorenew</span><span class="prepare-data">Prepare Data</span>
RSCSS に従うと、エレメントにはハイフンを使えません

2021-05-28 00:53 UTC, ryuta-oe commented on frontend/source/js/classes/TableData.js
> +        <span class="material-icons-outlined autorenew">autorenew</span><span class="prepare-pause-resume">Prepare Data</span>
以下に変更すればよいでしょうか？
class="Prepare data"

2021-05-28 04:09 UTC, penqe approved these changes
OKです！

2021-05-28 06:22 UTC, merged